apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: openshift-operators
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: app
  source:
    path: manifests
    repoURL: https://github.com/Millen93/test-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
