apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app
  namespace: openshift-operators
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc 
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

